### ISSUE TITLE
CDKManager.loadMolecule with Scyjava does not work

### ISSUE THREAD

**Issue by kozo2** [egonw/bacting#58]
## Bacting API method with unexpected output

loadMolecule did not work when importing CDKManager with scyjava.

![image](https://user-images.githubusercontent.com/12192/131824356-7a9b1dc2-4446-433e-a1bc-08c3932a8760.png)

### Expected Output

```
kegg_sdf will be a data object for the given input
```

### Actual Output

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-9f73bc61576b> in <module>()
----> 1 kegg_sdf = cdk.loadMolecule("./kegg.sdf")

TypeError: No matching overloads found for net.bioclipse.managers.CDKManager.loadMolecule(str), options are:
	public net.bioclipse.cdk.domain.ICDKMolecule net.bioclipse.managers.CDKManager.loadMolecule(java.io.InputStream,org.openscience.cdk.io.formats.IChemFormat) throws net.bioclipse.core.business.BioclipseException,java.io.IOException

```

## Additional context

You can reproduce the error with https://colab.research.google.com/drive/1RwXBVgClncDwascTbhhsFkuzPmgFl6ar?usp=sharing

**Comment by egonw** [comment]
Okay, I think this one is a bit more complicated. The same str/String issue likely, but not sure that it's the only thing to solve here. I also think both need a ScyJava example in the documentation, somewhere.

**Comment by egonw** [comment]
I ported the method you need, which will be part of the next release:

```python
from scyjava import config, jimport

config.add_endpoints('io.github.egonw.bacting:managers-cdk:0.0.24-SNAPSHOT')

workspaceRoot = "."
cdkClass = jimport("net.bioclipse.managers.CDKManager")
cdk = cdkClass(workspaceRoot)

heptane = cdk.loadMolecule("/Test/heptane.mol")

print(heptane)
```

**Comment by egonw** [comment]
I am going to release 0.0.24 now.

**Comment by egonw** [comment]
done.

**Comment by kozo2** [comment]
@egonw Thanks.
However, there seems to be a problem with the handling of the `loadMolecule` argument path string.
You can check it with https://colab.research.google.com/drive/1RwXBVgClncDwascTbhhsFkuzPmgFl6ar?usp=sharing

```
from scyjava import config, jimport
config.add_endpoints('io.github.egonw.bacting:managers-cdk:0.0.24')

workspaceRoot = "."
cdkClass = jimport("net.bioclipse.managers.CDKManager")
cdk = cdkClass(workspaceRoot)
# kegg_sdf = cdk.loadMolecule("/kegg.sdf") #this does not work
# kegg_sdf = cdk.loadMolecule("/content/kegg.sdf") #this also does not work
kegg_sdf = cdk.loadMolecule("/kegg.sdf") # this works but is not appropriate
```

**Comment by egonw** [comment]
Yes, this is a bit of Bioclipse legacy... everything is in a Project in the workspace. On disk this is just a folder.

So, your workspaceRoot = ".". In that folder make a subfolder "KEGG" and copy the `kegg.sdf` file into that folder. Then:

```pythong
kegg_sdf = cdk.loadMolecule("/KEGG/kegg.sdf")
```

**Comment by kozo2** [comment]
Thank you for the information.
I understand why you always put files under a certain directory.
