### ISSUE TITLE
Installation tries to sign with gpg and fails

### ISSUE THREAD

**Issue by Zethson** [egonw/bacting#8]
Dear @egonw,

when attempting to install with `mvn clean install` I run into:
```
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ bacting ---
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

The installation should not try to sign keys, or?
Am I missing something?

**Comment by egonw** [comment]
Oops. Yes, plz add `-Dgpg.skip`. I will update the instructions. Sorry for the inconvenience.

**Comment by egonw** [comment]
I reproduced this fix on a machine without GPG key. Unless someone tells me it doesn't work, I consider this one fixed.
